sudo: required
services:
  - docker
before_install:
  - docker build -t vspvijay/cloudnloud .
script:
  - echo "$name" | docker login -u "$value" --password-stdin
  - docker images
  - docker push vspvijay/cloudnloud
notifications:
  email:
    recipients:
      - vijayp05@gmail.com.com
    on_success: always
    on_failure: always
